services:
  db:
    image: postgres:14-alpine
    ports:
      - 5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build:
      context: ..
      dockerfile: example/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: development
      APP_NAME: postgres-instrumentation-example
      PORT: 3005
      PGPORT: 5432
      PGHOST: db
      PGUSER: postgres
      PGDATABASE: postgres
      PGPASSWORD: postgres
    ports:
      - 3005:3005

volumes:
  postgres_data:
